spring:
   security:
      oauth2:
         authorizationserver:
            client:
               client-1:
                  registration:
                     redirect-uris: https://oidcdebugger.com/debug, https://oauthdebugger.com/debug, https://springone.io/authorized, http://127.0.0.1:8081/login/oauth2/code/spring
                     client-id: client
                     client-secret: secret
                     client-authentication-methods: client_secret_basic
                     authorization-grant-types: client_credentials, authorization_code, refresh_token
                     scopes: user.read, user.write, roles, openid
                     require-authorization-consent: false
               client-2:
                  registration:
                     redirect-uris: https://oidcdebugger.com/debug, https://oauthdebugger.com/debug, https://springone.io/authorized, http://127.0.0.1:8081/login/oauth2/code/spring
                     client-id: client2
                     client-secret: secret2
                     client-authentication-methods: client_secret_basic
                     authorization-grant-types: client_credentials, authorization_code, refresh_token
                     scopes: user.read, user.write, roles, openid
                     require-authorization-consent: false

server:
   port: 8082

logging:
   level:
      org:
         springframework:
            security: TRACE