spring:
  #security:
    #oauth2:
      #authorizationserver:
        #client:
          #require-authorization-consent: false

          #client-1:
            #registration:
              #redirect-uris: https://oidcdebugger.com/debug, https://oauthdebugger.com/debug, https://springone.io/authorized, http://127.0.0.1:8081/login/oauth2/code/spring
              #client-id: client
              #client-secret: $2a$12$Ah/6RpokivnYEYhFy58pWeAt/3YZB7qtK6fH05tLoWXCTywgtFGOe #secret
              #client-authentication-methods: client_secret_basic
              #authorization-grant-types: client_credentials, authorization_code, refresh_token
              #scopes: user.read, user.write, roles, openid

          #client-2:
            #registration:
              #redirect-uris: https://oidcdebugger.com/debug, https://oauthdebugger.com/debug, https://springone.io/authorized, http://127.0.0.1:8081/login/oauth2/code/spring
              #client-id: client2
              #client-secret: $2a$12$OSv.3I9LIJ2Q1si9UmATwODq.JCykmUVkXpVVRBUXf9DHvILM2SFq #secret2
              #client-authentication-methods: client_secret_basic
              #authorization-grant-types: client_credentials, authorization_code, refresh_token
              #scopes: user.read, user.write, roles, openid

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate.default_schema: oauth
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non-contextual-creation: true
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.yml
    default-schema: oauth
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: sA#259979148307

preliquibase:
  sqlScriptReferences: classpath:/db/preliquibase/create_schema.sql

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: trace
    root: INFO
  file:
    path: src/main/resources/logs
    name: src/main/resources/logs/authorization-service.log